---
- name: Check OS version and family
  ansible.builtin.assert:
    that:
    - ansible_os_family == 'Windows'
    - ansible_distribution | regex_search('(Microsoft Windows Server 2022)')
    success_msg: "{{ ansible_distribution }} {{ ansible_distribution_major_version }} is the detected operating system."
    fail_msg: |
      This role can only be run against Windows Server 2022 editions.
      {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported.
  tags: always

- name: Set fact if Server Core
  ansible.builtin.set_fact:
    <%= $PLASTER_PARAM_VariablePrefix %>_server_core: true
  when: ansible_os_installation_type == 'Server Core'
  tags: always

- name: Execute the CAT 1 tasks
  ansible.builtin.import_tasks: cat1.yml
  when: <%= $PLASTER_PARAM_VariablePrefix %>_cat1
  tags: cat1

- name: Execute the CAT 2 tasks
  ansible.builtin.import_tasks: cat2.yml
  when: <%= $PLASTER_PARAM_VariablePrefix %>_cat2
  tags: cat2

- name: Execute the CAT 3 tasks
  ansible.builtin.import_tasks: cat3.yml
  when: <%= $PLASTER_PARAM_VariablePrefix %>_cat3
  tags: cat3
